spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: demo
  password: 1234

server:
  port: 7001

logging:
  level:
    ru.alina: debug





spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9094
      group-id: group



