#spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: demo
  password: 1234

server:
  port: 7001

logging:
  level:
    ru.alina: debug


spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9094
      group-id: group

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/fictional_bank





